# Generated by Django 5.0.1 on 2024-01-27 12:06

import TwojeGryApp.models
import django_enumfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TwojeGryApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="genre",
            field=django_enumfield.db.fields.EnumField(
                default=12, enum=TwojeGryApp.models.Genre
            ),
        ),
    ]
